### ISSUE TITLE
Cannot use text algebra in scala 3.1.0

### ISSUE THREAD

**Issue by custommonkey** [creativescala/doodle#111]
The definition of the `text` object in the `doodle.syntax` package object clashes with the definition of the `text` function in `TextSyntax`

Example:
```scala
    import doodle.java2d.algebra.Algebra
    import doodle.java2d.Drawing
    import doodle.syntax.*
    text[Algebra, Drawing]("scsdcs")
```

Compiler output:
```
Toplevel definition text is defined in
  /Users/jemartin/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/creativescala/doodle-core_3/0.10.0/doodle-core_3-0.10.0.jar(doodle/syntax/package.class)
and also in
  /Users/jemartin/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/creativescala/doodle-core_3/0.10.0/doodle-core_3-0.10.0.jar(doodle/syntax/TextSyntax.class)
One of these files should be removed from the classpath.
```

**Comment by noelwelsh** [comment]
Thanks for reporting this. Looks like a change from Scala 2 to Scala 3.
I'll think about the best way to address this. For now you can write
`text.text("foo")` and it should work.

**Comment by custommonkey** [comment]
Unfortunately `text.text("foo")` doesn't work either. Current work around has been to fork the repo and delete the text object.

**Comment by noelwelsh** [comment]
I think I'll follow the design in Cats and Cats Effect and shift "import everything" out of the package object and into an object named `all`. This will break existing code but 0.10 hasn't be officially released yet so it's ok as part of the first offical 0.10 release.

**Comment by noelwelsh** [comment]
[ ] Create `all` object in `doodle.syntax`
[ ] Update `image` syntax
[ ] Update documentation

**Comment by noelwelsh** [comment]
Should all be good to go in the next release.
