### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by joramnv** [creativescala/doodle#116]
Hi, SVG support was removed in this commit https://github.com/creativescala/doodle/commit/32fa36876c047cb88a5c8099e3bab13db3dc4f27. I am wondering what the plans are. Is SVG support coming back at some point in the near future?

**Comment by noelwelsh** [comment]
The project now lives at https://github.com/creativescala/doodle-svg It
requires a little bit more attention before it's ready to publish.

**Comment by noelwelsh** [comment]
Closing this as the Doodle SVG project has been published for a while.
