### ISSUE TITLE
Any convenient way to obtain an arbitrary image's height and width?

### ISSUE THREAD

**Issue by spamegg1** [creativescala/doodle#119]
I'd like to write a function
```scala
def boxify(i: Image): Image
```
which draws a rectangular box around the image `i`. If the image is a `Rectangle`, a `Triangle` or a `Circle` then it's easy to figure out the height / width. 

Is there a built-in way to do this in general? Like here: https://docs.racket-lang.org/teachpack/2htdpimage.html#%28part._.Image_.Properties%29

If not, how can I go about writing a function that calculates them? (It doesn't have to be very accurate, just a crude estimate of the height / width will do.)

Is there a different type other than `Image` that's more convenient for this?

**Comment by noelwelsh** [comment]
The `debug` method will draw the bounding box and origin for an `Image`. 

Otherwise your best option is to work directly with `Picture` and use the [`Size`](https://javadoc.io/doc/org.creativescala/doodle-docs_3/latest/doodle/algebra/Size.html) algebra, which will provide all the information you need. The 0.12 documentation describes how to work with `Picture`: https://creativescala.github.io/doodle/algebra/index.html

**Comment by spamegg1** [comment]
Thanks a lot!

**Comment by spamegg1** [comment]
Sorry for reopening this, but I really need help. Apologies for the long story below.

I was unable to use the 0.12 documentation because I was stuck on 0.11.2 due to #120 I tried to follow the documentation there:
```scala
import doodle.core.*
import doodle.syntax.all.*
import doodle.java2d.*

val picture = circle[Algebra, Drawing](100)
picture.height
```
and... YIKES!
```scala
res0: Picture[[F >: Nothing <: [_$1 >: Nothing <: Any] => Any] => Basic[F] & Bitmap[F] & Text[F], [A >: Nothing <: Any] => Finalized[Reification, A], Double] = doodle.algebra.Picture$$anon$1@6b1ad498
```
So I had to do some trick to switch to 0.12.0. To overcome #120, instead of
```scala
"org.creativescala"             %% "doodle"        % 0.11.2,
```
I had to use:
```scala
"org.creativescala"             %% "doodle-core"        % 0.12.0,
"org.creativescala"             %% "doodle-java2d"      % 0.12.0,
"org.creativescala"             %% "doodle-image"       % 0.12.0,
"org.creativescala"             %% "doodle-interact"    % 0.12.0,
"org.creativescala"             %% "doodle-turtle"      % 0.12.0,
"org.creativescala"             %% "doodle-golden"      % 0.12.0,
```
0.12.0 seems *vastly* different, and simplified, which is great. I decided to follow the example with `Basic` because it extends `Size`.
```scala
import doodle.core.*
import doodle.syntax.all.*
import doodle.language.Basic

val picture = circle[Basic](100)
picture.height
```
And I got
```scala
res0: Picture[Basic, Double] = doodle.syntax.SizeSyntax$$anon$1@21819987
```
Wow, that is MUCH better. I feel like I'm so close... but there is no way to get that `Double` value out, is there? (Because it's "trapped in a monad".)

I believe that the `Image` class should have convenient `height` and `width` methods that return `Double`. Here's my reasoning:
- Most beginner image exercises in Racket makes the learner compare images by width or height, or calculate the (approximate) area of an image, or sort a list of images by width/height/area, and so on. They can easily do that with `(image-height img)` which is built-in.
- Beginners should be able to easily access an image's width and height, without using any algebras, type parameters or any other advanced subject.
- There is not a single example in the documentation, or the entire Creative Scala book, of getting an image's height or width (as a pure `Double` value), which I find absolutely astounding (no offense).
- Doodle is about ease of use:
> Be Easy to Use
Doodle is designed to be easy to use, while keeping to the principles above. In particular we value ease-of-use above performance, though we will certainly optimize code where possible.
- I'm trying to create an alternative to the [How to Code courses](https://www.edx.org/course/how-to-code-simple-data) in Scala (because edX restricts access after 1-2 months), and Doodle is the best (and probably the only) option.

**I'd like to contribute to Doodle.** How can I add `.width` and `.height` methods to `Image` (or even `Picture`)? The only relevant thing I could find is `doodle.algebra.generic.FinalizedOps` which has a `boundingBox` method.

**Comment by spamegg1** [comment]
For others who might be wondering about the same thing: I am able to get by mostly with the following rudimentary method, which is good enough for simple educational purposes (Scala 3 extension methods are awesome! They were created for exactly this scenario):
```scala
extension (image: Image)
  def size: Double = image match
    case OpenPath(elements)            => 0.0
    case ClosedPath(elements)          => 0.0
    case Text(get)                     => get.size.toDouble
    case Circle(d)                     => d * d * math.Pi
    case Rectangle(w, h)               => w * h
    case Triangle(w, h)                => w * h / 2
    case Beside(l, r)                  => l.size + r.size
    case Above(l, r)                   => l.size + r.size
    case On(t, b)                      => math.max(t.size, b.size)
    case At(image, x, y)               => image.size
    case Transform(tx, i)              => i.size
    case StrokeWidth(image, width)     => image.size
    case StrokeColor(image, color)     => image.size
    case FillColor(image, color)       => image.size
    case FillGradient(image, gradient) => image.size
    case NoStroke(image)               => image.size
    case NoFill(image)                 => image.size
    case Font(image, font)             => image.size
    case Debug(image, color)           => image.size
    case Empty                         => 0.0
```
Obviously this isn't an accurate measure of "area" but it's enough.

**Comment by noelwelsh** [comment]
I'm glad to managed to get a solution that works for you. A few notes about this:

* a loose bounding box for a bezier curve is defined by the control points. You could use this to calculate the size of a path.
* a circle is defined by diameter, not radius, so I think the equation for `Circle` should be `d * math.Pi`
