### ISSUE TITLE
Version 0.12.0 not available on Maven

### ISSUE THREAD

**Issue by spamegg1** [creativescala/doodle#120]
![Screenshot from 2023-01-07 23-25-04](https://user-images.githubusercontent.com/4255997/211169161-df7a7125-5936-4909-ac0b-36fda790561b.png)

(Firstly, `master` seems to have been renamed to `main`.)

Using the above instructions in a Scala 3 project (Sbt 1.8.2 latest, Scala 3.2.1, Java 11) leads to the error:
```scala
sbt:scala-abc> compile
[info] Updating 
[info] Resolved  dependencies
[warn] 
[warn]  Note: Unresolved dependencies path:
[error] stack trace is suppressed; run last update for the full output
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.creativescala:doodle_3:0.12.0
[error]   Not found
[error]   Not found
[error]   not found: /home/spam/.ivy2/localorg.creativescala/doodle_3/0.12.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/creativescala/doodle_3/0.12.0/doodle_3-0.12.0.pom
[error] Total time: 3 s, completed Jan 7, 2023, 11:22:15 PM
```

Looking here, there isn't a 0.12.0 available: https://repo1.maven.org/maven2/org/creativescala/doodle_3/

Also 0.12.0 not available for Scala 2.13 https://repo1.maven.org/maven2/org/creativescala/doodle_2.13/

Strangely some of the components have 0.12.0 available, such as https://repo1.maven.org/maven2/org/creativescala/doodle-core_3/

**Comment by noelwelsh** [comment]
Thanks for reporting this. Looks like the aggregate project (`doodle`) didn't get published, though the individual components (`doodle-core` etc.) did. I will look into it.

**Comment by noelwelsh** [comment]
I've released 0.14.0, which is released correctly. Thanks again for the report.

**Comment by spamegg1** [comment]
Documentation is still confusing. 
There is 0.10.1 here https://www.creativescala.org/doodle/
There is 0.13.0 here https://creativescala.github.io/doodle/
And this page is 404 https://creativescala.github.io/

**Comment by noelwelsh** [comment]
Gotcha. I'll work on that next.

**Comment by noelwelsh** [comment]
Should be all done now.

**Comment by spamegg1** [comment]
Found another (unrelated) 404 at https://www.creativescala.org/case-study-forms
Doodle Explore shows 0.13.0 https://www.creativescala.org/doodle-explore/ but latest on Maven is 0.14.0.

**Comment by spamegg1** [comment]
I guess it's OK to close this now? It's mostly done (thanks!), my last comment has some minor things. Maybe I should open a separate issue for those.
