### ISSUE TITLE
Extend `Image` layout operations

### ISSUE THREAD

**Issue by noelwelsh** [creativescala/doodle#122]
* [X] add `margin`
* [x] add `originAt`
* [ ] allow `at` and `originAt` to use landmarks

This will bring `Image` inline with `Picture`.

It's not 100% clear this is necessary, as `Image` is becoming less attractive due to usability improvements to `Picture`.

**Comment by AishwaryaSatpute1** [comment]
I want to contribute on this issue , will you please assign this issue to me ?

**Comment by noelwelsh** [comment]
> I want to contribute on this issue , will you please assign this issue to me ?

I've assigned you, but in general I'm trying to keep the development process for Doodle as lightweight as possible. A simple issue this doesn't require any coordination so I encourage people to just submit PRs. 

If there was a complex issue that would require coordination, but so far I've done all such work on Doodle by myself (as best I can recall.)
