### ISSUE TITLE
Extend stroke styling for `Image`

### ISSUE THREAD

**Issue by noelwelsh** [creativescala/doodle#123]
Add `strokeJoin`, `strokeCap`, and `strokeDash` to `Image`, to provide all the features of the `Style` algebra.

**Comment by pratyaksh1610** [comment]
I would like to contribute to this project, I have set up the project and have also mailed the concerned mentor.

**Comment by pratyaksh1610** [comment]
I need some guidance as this is my first time contributing to Scala, and I am highly interested.
