### ISSUE TITLE
small typo(?) in `Frame`

### ISSUE THREAD

**Issue by spamegg1** [creativescala/doodle#125]
I noticed the changes to the `Frame` API in the latest version as it broke some of my Reactor code (was an easy fix).

I noticed that the [wthCenterAtOrigin method](https://github.com/creativescala/doodle/blob/v0.17.0/java2d/src/main/scala/doodle/java2d/effect/Frame.scala#L78) is... misspelled? All the other methods start with `with...`

**Comment by noelwelsh** [comment]
Thanks for pointing that out. That's an annoying mistake on my behalf. I'll make a new release soon.
