### ISSUE TITLE
Set window title?

### ISSUE THREAD

**Issue by xanderdunn** [creativescala/doodle#14]
Right now the window that doodle opens to draw an image is always titled "Doodle."  Is there any way to change this? 

<img width="195" alt="screen shot 2015-08-04 at 21 52 35" src="https://cloud.githubusercontent.com/assets/1313618/9078435/24757d7e-3af3-11e5-9e06-372d418a604c.png">

**Comment by noelwelsh** [comment]
Not at present. It should be easy to add, but I have other priorities right now. I'll add this to the queue.

**Comment by xanderdunn** [comment]
@noelwelsh Cool, thanks!  Yeah, it's not a top priority.

**Comment by noelwelsh** [comment]
The `java2d` `Frame` allows this in 0.9.
