### ISSUE TITLE
Consistent naming of writers

### ISSUE THREAD

**Issue by noelwelsh** [creativescala/doodle#146]
There are several types that convert a `Picture` into something else:

* `Writer`
* `Base64`
* `BufferedImageConverter`

There will probably be a lot more in the future. Let's name this concept and have a consistent naming scheme for the types that implement it. 

I propose calling this a writer. Methods on different writers will be different (e.g. a `FileWriter` will take a file name, where as a `Base64Writer` will not.) but it is possible to implement a marker trait, as is done for `Algebra` and `Format`.

* [ ] Implement `Writer` marker trait
* [ ] Update existing `Writer`, `Base64` etc to extend marker trait
* [ ] Rename to `FileWriter`, `Base64Writer`, etc. for consistent naming 
* [ ] Update syntax accordingly
* [ ] Document

**Comment by jCabala** [comment]
Should the documentation be written in the `effect` specific `README.md` file?
<img width="209" alt="image" src="https://github.com/creativescala/doodle/assets/79060739/aebe1fd0-52d8-482c-af9e-630c3cbca51b">

**Comment by noelwelsh** [comment]
Documentation lives here: https://github.com/creativescala/doodle/blob/main/docs/src/pages/README.md
