### ISSUE TITLE
Abstract default frame

### ISSUE THREAD

**Issue by noelwelsh** [creativescala/doodle#148]
Many `Writer` methods will be more convenient to call if the user doesn't have to specify a `Frame` parameter but instead some sensible default is used. There is already a default frame but it is coupled to rendering (see `DefaultRenderer`). So goal of this work is to abstract the default frame into it's own type class so it can be used in more contexts.

* [ ] Create `DefaultFrame` type class
* [ ] Adjust existing uses of `DefaultRenderer` to use this
* [ ] Document

**Comment by jCabala** [comment]
`Frame.default` is used as a default frame. Is this issue asking to remove it and change all usecases into using another class that extends from `Frame`?

**Comment by noelwelsh** [comment]
I'll implement this one. It's quite simple is implementation but harder to explain.

**Comment by noelwelsh** [comment]
PR: https://github.com/creativescala/doodle/pull/153
