### ISSUE TITLE
Transformations or Multiple Images per Canvas?

### ISSUE THREAD

**Issue by xanderdunn** [creativescala/doodle#15]
It looks like right now Doodle doesn't have the ability to draw multiple doodle.core.Image objects in the same context?  Each `draw()` call opens a new rendering window.  

It also looks like Doodle doesn't support transitions?  That is, moving something once it's been drawn on a canvas?  

Does doodle plan to add these things?  Is there any way I might do drawing with Doodle's high level API and then access the lower level Java2D objects to do more complicated things like transitions and adding other drawings to a canvas?

**Comment by noelwelsh** [comment]
There is currently basic support for animations. Take a look at `Orbit.scala` in the examples. I have an immediate task to make this a lot better.

You can add multiple drawings to the same window with the current API, but it's not obvious how to do this unless you know the API in quite some depth. I'll look at making this easier, but it will happen after the animation improvements. 

I don't have a reliable Internet connection at the moment so my responses will be delayed.

**Comment by ddemange** [comment]
This would indeed be useful. Any update on this?

Reading the source code of Animation and Orbit, I couldn't find a easy way to display the animation with the Standard Interpreter. I'm planning to use Doodle to teach Scala. I'd like to stay away from the js backend, and rather stick to a regular, simple, Scala app.

Am I missing something? 

Thanks

**Comment by noelwelsh** [comment]
@ddemange Is your main interest animation or just displaying multiple images on the canvas?

The rough plan for animations is some kind of FRP system. Could probably build it out of existing parts, like `fs2` or `monix`, and a few changes to the backend.

What is your time frame, and what are teaching goals around animations?

**Comment by ddemange** [comment]
@noelwelsh Sorry for the late reply.

I'd like to get ready for late october. 

This is a course I adapt from a previous one, in which I was relying on Racket, and the universe.rkt teachpack. There, I could easily ask the students to write all the mechanics of the game, while I was taking care of providing the right call to big-bang and potential required conversions. I found universe/big-bang really smooth to use (and to explain to the students while not having to wave hands too much -- this is something I was not ashamed to show).

I don't have teaching goals around animations, per se. Rather, I see it as a way of both doing entertaining program exercises. Having something similar to universe/big-bang would be would save me the re-coding of a whole GUI every time.

Perhaps a simple reactive framework -- limited to clock ticks -- would be enough for me. Something like a simple state monad, where at each step, the state is "printed" as an doodle Image. Typical workflow: 
- define the type State
- a conversion function show: State => Image
- a step function : State => State
- define a initial state init : State
- and the step function would be applied (starting from init) at every clock tic, re-showing the current State in the same single frame.

I can see in Orbit.scala some of the above elements, but I fail to see how to use this in the current version of doodle (typically, draw is opening a new Frame each time called).

**Comment by noelwelsh** [comment]
In 0.9 you can `draw` to a given `Frame`, which allows animations and multiple images per frame. There is animation support, and the `Reactor` package provides animations in a similar style to universe/big-bang and the reactors in Pyret.
