### ISSUE TITLE
Switch to using fixedRate() instead of fixedDelay() for Reactor

### ISSUE THREAD

**Issue by lego-eden** [creativescala/doodle#170]
In [BaseReactor](https://github.com/creativescala/doodle/blob/main/reactor/shared/src/main/scala/doodle/reactor/BaseReactor.scala) I noticed that the method used to generate the `Stream[IO, Command]` of states is `Stream.fixedDelay[IO]`. Switching to using `Stream.fixedRate[IO]` might result in smoother motion with less microstutters. At least I expected the frames to be generated at a fixed rate and not with a fixed delay.
![image](https://github.com/user-attachments/assets/d10c2f48-a0f8-4bbc-bf59-03fed0b10d9a)

**Comment by noelwelsh** [comment]
Thanks!
