### ISSUE TITLE
Frame instantiation does not respect width and height overrides

### ISSUE THREAD

**Issue by ludwiggj** [creativescala/doodle#179]
Following code instantiates a frame with width and height of 300.

```
package effect

import cats.effect.*
import doodle.core.*
import doodle.java2d.*
import doodle.java2d.effect.Frame
import doodle.syntax.all.*
import scala.concurrent.duration.*

object FrameBug extends IOApp {
  def run(args: List[String]): IO[ExitCode] = {
    val frame = Frame.default.withSize(width = 300, height = 300).withBackground(Color.midnightBlue)
    frame
      .canvas()
      .use { _ =>
        IO.sleep(5.seconds) >> IO.pure(ExitCode.Success)
      }
  }
}
```

Expected result:

Frame with width and height of 300.
![doodleFrameExpected](https://github.com/user-attachments/assets/038d5070-3625-4363-9441-08772b09d688)

Actual result:

A frame with minimal width and height.
![doodleFrameActual](https://github.com/user-attachments/assets/b4cce9d5-6593-45e5-ae00-25b776ef8855)

**Comment by noelwelsh** [comment]
Thanks. I've pushed a fix.
