### ISSUE TITLE
Reorder how context transforms are applied

### ISSUE THREAD

**Issue by noelwelsh** [creativescala/doodle#36]
Doodle currently applies the inner most `ContextTransform`. E.g.

`circle(10).fillColor(Color.red).fillColor(Color.blue)`

will produce a red circle. A more sensible semantics is to produce a blue circle.

**Comment by dabar347** [comment]
Additionally circle(10).fillColor(Color.red).lineWidth(10.0) and circle(10).lineWidth(10.0).fillColor(Color.red) both produce circle with standard line width (fill color seem to be overlay/override it). Without fillColor the line width is correct

**Comment by noelwelsh** [comment]
Fixed in 0.9
