### ISSUE TITLE
Build Scaladoc

### ISSUE THREAD

**Issue by noelwelsh** [creativescala/doodle#49]
It would be nice to build Doodle Scaladoc.

**Comment by ddemange** [comment]
Yes, indeed!
BTW, when building a triangle, what do represent the two parameters?
Obviously (correct me if I'm wrong), the triangle looks isosceles, and the first parameter defines the size of the horizontal basis. What does represent h ? Is it the size of the two other sides of the triangle, or rather the height of the triangle ? 
Another question is: what's the unit used for these parameters ? Are they pixels, or something else?
Thanks

**Comment by noelwelsh** [comment]
Triangle is represented by width and height. Units are (usually) pixels but there isn't a strict interpretation for them.

**Comment by noelwelsh** [comment]
https://www.creativescala.org/doodle/ links to the ScalaDoc
