### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by krishna444** [creativescala/doodle#72]
I am very new to this library. I got a book "Creative Scala"; to follow this book, I need to install this library. I added the dependent library in my build.sbt file.

_libraryDependencies += "creativescala.org" %% "doodle" % "0.9.0-SNAPSHOT"_

 But build does not work, it says the library is not available in MAVEN repository. 

I tried it to create a JAR file from your source code, still I could not build it. 

Is there any work *.jar file, so that I can directly use in my sample project. 

Thanks alot !

**Comment by noelwelsh** [comment]
Easiest way to get started is to use this project: https://github.com/underscoreio/creative-scala-template

Does that work for you?

**Comment by krishna444** [comment]
Hi noelwelsch,

it is working, thanks!

**Comment by noelwelsh** [comment]
Great! I'll close this issue then.
