### ISSUE TITLE
publish to Maven Central?

### ISSUE THREAD

**Issue by SethTisue** [creativescala/doodle#74]
for a getting-started library like this, I think it would be better to remove any possible road bump for newcomers. only having the library available via a custom resolver is a road bump; seen on Gitter today:

> does anyone know where I can find the scala doodle lib ? can't find it on mvn central

**Comment by noelwelsh** [comment]
Agreed. I have attempted to setup Maven central under the creativescala.org domain. I might have even published snapshots. I don't have clue what I'm doing so probably I've messed it all up.

**Comment by SethTisue** [comment]
I see 0.9.0 on Maven Central: https://search.maven.org/artifact/org.creativescala/doodle_2.12/0.9.0/jar

is https://github.com/underscoreio/creative-scala-template/blob/master/build.sbt ready to be upgraded from 0.8.3 to 0.9.0, or are there are other coordinated changes that need to happen first?

**Comment by noelwelsh** [comment]
The Creative Scala template is used for working with the book Creative Scala, and that book still uses Doodle 0.8.3. Rewriting it will be some work (not least because it is a guaranteed OOM crash trying to build the book with Tut.) So for now the template will stay on 0.8.3.

**Comment by SethTisue** [comment]
> Rewriting it will be some work (not least because it is a guaranteed OOM crash trying to build the book with Tut.)

is there a ticket on the underlying issue there? I'm wondering if https://github.com/scalameta/mdoc might be a workable alternative

**Comment by noelwelsh** [comment]
Transition to `mdoc` is happening [here](https://github.com/underscoreio/creative-scala/tree/feature/mdoc)
