### ISSUE TITLE
Update write options for images to include Base64 string

### ISSUE THREAD

**Issue by micausti** [creativescala/doodle#77]
I would like to post images generated from doodle to Twitter. The required format is Base 64 string. Currently, doodle only allows writing to png, jpg, or gif. Can you please update to allow the user to write to a Base64 string to make this process easier? Thanks!

**Comment by micausti** [comment]
I ended up finding a different way to do this, so I don't need the feature any longer. I think I remember you saying that you may have already written it, but I just wanted to let you know there's no rush since I have a different way. Thanks!

**Comment by mcanlas** [comment]
For posterity, could you describe the process you ended up using?

**Comment by micausti** [comment]
I found a library (https://github.com/DanielaSfregola/twitter4s) which makes it easy to post the png, jpg, or jif as is.
