### ISSUE TITLE
Coordinates edges

### ISSUE THREAD

**Issue by gilcu2** [creativescala/doodle#81]
I would like to show the coordinate edges so when I see the drawing I can have the context. What can I do?
Thanks
Reynaldo

**Comment by noelwelsh** [comment]
Hi,

 Would displaying the bounding boxes and origins do what you want?

**Comment by noelwelsh** [comment]
Further questions: what version of Doodle are you using? If you are using 0.9, are you using the `Image` data type or the tagless final algebras directly?

**Comment by gilcu2** [comment]
Hi, yes.

**Comment by noelwelsh** [comment]
You can render origins by  simply drawing a circle `on` any image. If you use 0.9 you can access the width and height of the bounding box using the `Size` algebra, and from that you can draw the bounding box.
