### ISSUE TITLE
IntelliJ showing errors when playing around with Examples

### ISSUE THREAD

**Issue by clemniem** [creativescala/doodle#98]
Hello, 

I am not sure if this is the right place to ask about this, but the Gitter looked not really used anymore.

Just found this awesome lib and wanted to try it out a little bit, but IntelliJ was showing me always some missing implicits when doing very simple stuff like: 

```scala
import doodle.core._
import doodle.image._
import doodle.image.syntax._

// those two imports are not mentioned in doc, Edit: this is actually mentioned, don't know where I was looking...
// but I figured out somehow that they should be needed
import doodle.java2d._  
import doodle.java2d.effect._

object SimpleCircle extends App {
  val circle = Image.circle(10).fillColor(Color.red)

  circle.draw() // IntelliJ shows Error --> No implicits found for parameter renderer: DefaultRenderer[Alg_, F_, Frame_, Canvas_]

}
```

After some time googling I found that this is something from Cats, where Intellij cannot infer the Type, so this fixed the issue: 

```scala
  circle.draw[Algebra, Drawing, Frame, Canvas]() // No error
```

Guess this is a no-brainer, when already used to the Cats Lib but since I never really used it this was quite unknown to me. So probably a good Idea to mention this in the First-Steps, to not have newbies blocked at the first very simple example. I can also do a PR but maybe this is already planned for somewhere, so I thought asking first about this would make sense. 

Have a great Day and thanks for the cool Library!
clem

**Comment by noelwelsh** [comment]
Can you tell me where in the docs you would expect to see the imports mentioned? I see them on, for example, the Doodle home page so I want to know where you were looking.

You shouldn't need to write

```scala
 circle.draw[Algebra, Drawing, Frame, Canvas]()
```

That's surprising to me. I don't use IntelliJ, though.

**Comment by Jaxii** [comment]
> ```scala
>  circle.draw[Algebra, Drawing, Frame, Canvas]()
> ```

IntelliJ throws errors for me as well and won't compile without .draw[Algebra, Drawing, Frame, Canvas]() as opposed to .draw()

**Comment by noelwelsh** [comment]
Ok, thanks. I will update the docs to try to make the imports more explicit.

I have to admit I don't have much energy for fighting IntelliJ issues. I don't know where to even start with that one.

**Comment by clemniem** [comment]
> I have to admit I don't have much energy for fighting IntelliJ issues. I don't know where to even start with that one.

Totally understandable! I will try to find out the issue, as there is a bug for that on the intellij side. Will post it here later. As a simple hint that there is an issue with intellij and not the Doodle Lib would have already helped me a lot, since I thought I am using Doodle wrong.

**Comment by clemniem** [comment]
I found now on which documentation page I was on, without the imports to draw: https://www.creativescala.org/doodle/image/index.html

And here is the StackOverflow Answer that helped me figure out what is wrong: https://stackoverflow.com/questions/34695616/false-errors-when-using-cats-library-in-intellij

My proposal would be to just include a small warning: 

> **Attention IntelliJ Users**
> The Scala Plugin of IntelliJ still has an open [Bug](https://youtrack.jetbrains.com/issue/SCL-10259) which cannot resolve implicits correctly. Therefore the above example might give you an Error warning in Line XX. To fix it in this small example use `circle.draw[Algebra, Drawing, Frame, Canvas]()`. Please use any Text Editor and sbt directly to get a better experience using this Library.

This is just a proposal, but something along those lines should get Beginners on board and more experienced Devs will know what to do with it. Maybe there is also a way to disable this Error Warning in the Scala Plugin, but I would have to double check.

**Comment by noelwelsh** [comment]
Finally fixed this. Thanks for reporting!
